### ISSUE TITLE
GPL Violation

### ISSUE THREAD

**Issue by ading2210** [NoahNinja100/school#1]
Hi,

I'm the original creator of [ading2210/edpuzzle-answers](https://github.com/ading2210/edpuzzle-answers), which is licensed under the [GNU GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html). It's not legal to redistribute GPL licensed code without also licensing it under the GPL and crediting the original. I'm fine with people reuploading my work, but at least credit the original. It even looks like you went out of your way to [remove the credits](https://github.com/NoahNinja100/school/blob/d1e27aff58bd7fe91a28fbe979555144ed4ef28b/edpuzzle/script.js#L134) from within the program. Could you at least credit my work and include a copy of the GPL so I don't have to submit a DMCA takedown? 

Thanks,
ading2210

**Comment by NoahNinja100** [comment]
Oh Sorry

**Comment by NoahNinja100** [comment]
I added the credit and license
